### ISSUE TITLE
Choice.prototype.addSeparator

### ISSUE THREAD

**Issue by DevJonTaylor** [DevJonTaylor/sweaty-shell-team#6]
When attempting to add a new separator it throws a TypeError

```bash
TypeError: Cannot read properties of undefined (reading 'type')
    at C:\coding_bootcamp\challenges\module_10\sweat-shell-team\node_modules\inquirer\lib\objects\choices.js:22:15
    at Array.map (<anonymous>)
    at new Choices (C:\coding_bootcamp\challenges\module_10\sweat-shell-team\node_modules\inquirer\lib\objects\choices.js:21:28)
    at new Prompt (C:\coding_bootcamp\challenges\module_10\sweat-shell-team\node_modules\inquirer\lib\prompts\base.js:48:26)
    at new ListPrompt (C:\coding_bootcamp\challenges\module_10\sweat-shell-team\node_modules\inquirer\lib\prompts\list.js:23:5)
    at PromptUI.fetchAnswer (C:\coding_bootcamp\challenges\module_10\sweat-shell-team\node_modules\inquirer\lib\ui\prompt.js:106:25)
    at doInnerSub (C:\coding_bootcamp\challenges\module_10\sweat-shell-team\node_modules\rxjs\dist\cjs\internal\operators\mergeInternals.js:22:31)
    at outerNext (C:\coding_bootcamp\challenges\module_10\sweat-shell-team\node_modules\rxjs\dist\cjs\internal\operators\mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (C:\coding_bootcamp\challenges\module_10\sweat-shell-team\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (C:\coding_bootcamp\challenges\module_10\sweat-shell-team\node_modules\rxjs\dist\cjs\internal\Subscriber.js:51:18)```

**Comment by DevJonTaylor** [comment]
Issue resolved, the separator was being treated as a Choice class and we were calling toObject on the Separator class which does not exists.  A check is in place and the List.test.js has been updated to reflect this for future updates.
